bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")

# Fetch the ARM GNU toolchain
bazel_dep(name = "toolchains_arm_gnu", version = "1.0.1")

arm_toolchain = use_extension("@toolchains_arm_gnu//:extensions.bzl", "arm_toolchain")
arm_toolchain.aarch64_none_linux_gnu(
    version = "13.2.1",
)
use_repo(arm_toolchain, "aarch64_none_linux_gnu")

# For Bzlmod (MODULE.bazel)
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "abb61a688167623088f8768cc9264798df6a9d10", # Use the latest commit hash
)
